### ISSUE TITLE
Cannot create service - must be rewritten using the code contracts binary rewriter

### ISSUE THREAD

**Issue by thnk2wn** [splunk/splunk-sdk-csharp-pcl#42] opened 2015-09-29 21:21 UTC
When creating the service I get the following error popup in Visual Studio 2015 Enterprise:

 "An Assembly (probably "Splunk.Client") must be rewritten using the code contracts binary rewriter (CCRewrite)...

And I cannot proceed. 

Splunk.Client 2.2.0

**Comment by shakeelmohamed** [comment] 2015-09-29 21:25
Hi @thnk2wn,

Thanks for letting us know, we're currently working on this in the `bugfix/code-contracts` branch

**Comment by thnk2wn** [comment] 2015-09-29 21:30
Thanks, please let me know when I can try again!

**Comment by mtevenan-splunk** [comment] 2015-09-29 21:46
Hi Geoff,

The documentation covers this. Please verify you've followed all the instructions on dev.splunk.com/view/SP-CAAAEYM<http://dev.splunk.com/view/SP-CAAAEYM>, and then let us know if you're still having trouble.

Thanks,
Matt

--
Matt Tevenan
Sr. Technical Writer
Splunk Inc. | www.splunk.com<http://www.splunk.com>

On Sep 29, 2015, at 2:21 PM, Geoff Hudik <notifications@github.com<mailto:notifications@github.com>> wrote:


When creating the service I get the following error popup in Visual Studio 2015 Enterprise:

"An Assembly (probably "Splunk.Client") must be rewritten using the code contracts binary rewriter (CCRewrite)...

And I cannot proceed.

Splunk.Client 2.2.0

**Comment by thnk2wn** [comment] 2015-09-29 21:53
@mtevenan-splunk Thanks. It would probably be helpful to add a link to that page to the readme. I arrived at this repo via nuget, I wasn't aware of that dev page.

**Comment by thnk2wn** [comment] 2015-09-29 22:00
I installed that and checked Perform Runtime Contract Checking but still receive the error. Is there something additional I need to setup on the Code Contracts tab page?

![code contracts](https://cloud.githubusercontent.com/assets/120529/10179419/b3cf4872-66ba-11e5-96ac-4a9cbcea45cb.png)

**Comment by glennblock** [comment] 2015-09-30 00:06
There shouldn't be, it just requires the rewriter. However, we're in the
process of updating the SDK and will re-release it in the next few days
without requiring you to have the rewriter.

**Comment by shakeelmohamed** [comment] 2015-10-02 03:26
Hi @thnk2wn, we've just released v2.2.1 addressing this! Thanks for the bug report

**Comment by shakeelmohamed** [comment] 2015-10-03 01:55
This is still an issue in the v2.2.1 nuget packages. We'll be investigating this some more next week, stay tuned

**Comment by glennblock** [comment] 2015-10-03 02:05
It looks like the issue is due to something on the MyGet end. We let MyGet
build our packages. We are looking into it. Thanks for your patience.

**Comment by shakeelmohamed** [comment] 2015-10-07 00:34
Hi @thnk2wn,

We've released v2.2.2 on nuget.
I've verified there are no code contracts errors when running a simple project in VS 2013 & 2015.
Please test it out and let us know, thanks again for your patience!

**Comment by muratoflu** [comment] 2015-10-07 07:09
I came across the same issue where I resolved by rebuilding the entire pcl
library solution in its seperate folder and use the binaries generated by
that. Seems like nuget binaries just dont work for some reason or another.
7 Eki 2015 03:34 tarihinde "Shakeel Mohamed" <notifications@github.com>
yazdı:

**Comment by shakeelmohamed** [comment] 2015-10-07 16:40
Hi @muratoflu,

Have you tried v2.2.2 from Nuget?

**Comment by reminvestor** [comment] 2015-11-18 18:26
I am using the latest v2.2.2 from Nuget with VS 2013 and I still get this issue after installing code contracts.

**Comment by glennblock** [comment] 2015-11-18 18:43
Have you updated to the latest nuget client?

**Comment by EfrainGonzalezBC** [comment] 2017-06-12 14:20
Have VS2015 Nuget v.2.2.2 and still have the same issue. R u guys in Splunk planning to work on this issue soon?

**Comment by shakeelmohamed** [comment] 2017-06-12 17:40
@EfrainGonzalezBC this should be fixed in later versions. Can you try v2.2.6?

**Comment by rahulisola** [comment] 2017-06-14 17:26
Hello all,
I have a weird issue here. Project works fine with the correct options chosen in Code Contracts with Splunk.Client 2.2.5. But when I update to 2.2.6, it fails with the error even when Code Contracts is selected. I go back to 2.2.5 and it works again.

**Comment by shakeelmohamed** [comment] 2017-06-14 18:36
Thanks for the update @rahulisola

**Comment by rahulisola** [comment] 2017-06-14 18:40
@shakeelmohamed No problem. Happy to help.
Feel free to reach out if you need any information from my side or any help in testing a fix.

**Comment by SaiSK88** [comment] 2017-08-16 05:41
@shakeelmohamed,

I am using VS 2017 and Splunk.Client 2.2.6 still I am getting "An Assembly (probably "Splunk.Client") must be rewritten using the code contracts binary rewriter (CCRewrite)".

Please suggest how this can be fixed?

Regards,
Sai

**Comment by Gammeldags** [comment] 2017-09-04 15:01
Version 2.2.6 does not work, CCRewriter does not work with VS2017,
but version 2.2.5 does not make these problems for me

**Comment by cidico** [comment] 2018-01-23 18:24
I'm having the same issue here with VS 2015 and 2017.
Even using the plugin for Code Contracts. Any tips on how to solve it?!
Thanks in advance...

![image](https://user-images.githubusercontent.com/3927895/35293098-d08ee324-0059-11e8-8ce8-3dc6c4a0b3a4.png)

**Comment by ThiloL** [comment] 2018-02-09 16:23
Hey splunk! Are you there.
Fix this CCRewrite stuff immediately.

**Comment by shakeelmohamed** [comment] 2018-03-05 18:16
Hey folks, we've been unable to re-produce the issue in house and that's the main reason we don't have a fix up yet. We're more than happy to accept a pull request if anyone can determine a fix

**Comment by yuriyzotov** [comment] 2018-03-13 06:57
Have the same Issue on VS2017 and Splunk.Client 2.2.6
When you will able to fix it?
To reproduce just add your NUGET to the solution and see the error

**Comment by martinmine** [comment] 2018-04-13 07:14
Also seeing this on Splunk.Client 2.2.7 from NuGet.org (VS2017/.NET Framework 4.7.1). Using version 2.2.5 as suggested by @Gammeldags (ironically, their username means old in Norwegian)

**Comment by martinmine** [comment] 2018-04-13 13:01
@shakeelmohamed Could this be an issue in your build system? I have investigated this a bit and the only difference I can see which could have an impact is the build system being misconfigured. I will do some more investigation and get back on this.

**Comment by shakeelmohamed** [comment] 2018-04-13 18:39
> Could this be an issue in your build system?
@martinmine It's certainly possible, but unfortunately we do not currently have the bandwidth to investigate this issue

**Comment by martinmine** [comment] 2018-04-13 19:56
@shakeelmohamed are you saying you don't have bandwidth to download a newer version of Visual Studio?

**Comment by shakeelmohamed** [comment] 2018-04-16 18:10
@martinmine As much as it pains me to admit it, yes

**Comment by martinmine** [comment] 2018-04-16 19:33
@shakeelmohamed Damn, that is resource constrained. How about getting a VM in the cloud to run VS for you or something?

**Comment by poparosa** [comment] 2018-05-24 19:21
I have uploaded working libraries to my GitHub repository.  It can be found here: 
https://github.com/poparosa/Splunk.Client

**Comment by martinmine** [comment] 2018-05-26 12:00
@poparosa you could also just use the code in the PR that I linked above; your repo only contains the DLL files (why?).

**Comment by darkonejr** [comment] 2018-05-31 22:34
This is a blocker for migrating our project to .NET Core (need a working library with both a recent Systems.Collections.Immutable and the Code Contract issue resolved).   @shakeelmohamed if you don't have time to work on this issue yourself, can you at least merge #79 and release, we're no worse off at this point...

**Comment by shakeelmohamed** [comment] 2018-06-01 19:08
Hi all, we've merged #79 (huge thanks to @martinmine!). We will look at getting a release out next week, thank you for your patience.

**Comment by darkonejr** [comment] 2018-09-28 17:35
He all, it's been a while, but it looks like this is still broken.  While System.Collections.Immutable has been updated to 1.3.1 in the .nuspec and package.config,  Splunk.Client.csproj still has a reference to 1.1.37....

**Comment by darkonejr** [comment] 2018-09-28 18:11
I've create PR #84  to correct the issue with S.C.I. please review and let me know if you see any issues with this.

**Comment by ncanumalla-splunk** [comment] 2022-11-09 19:56
This SDK is [deprecated](https://github.com/splunk/splunk-sdk-csharp-pcl#deprecation-notice) and no longer under active development.

**Closed by ncanumalla-splunk** 2022-11-09 19:56 UTC
Labels: bug
